# Generated by Django 4.2.20 on 2025-03-13 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_monthlyincome_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyincome',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyincome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_incomes', to=settings.AUTH_USER_MODEL),
        ),
    ]
